module.exports = {
  plugins: ["regexp"],
  rules: {
    "regexp/match-any": "error",
    "regexp/no-assertion-capturing-group": "error",
    "regexp/no-dupe-characters-character-class": "error",
    "regexp/no-empty-group": "error",
    "regexp/no-empty-lookarounds-assertion": "error",
    "regexp/no-escape-backspace": "error",
    "regexp/no-invisible-character": "error",
    "regexp/no-octal": "error",
    "regexp/no-useless-exactly-quantifier": "error",
    "regexp/no-useless-two-nums-quantifier": "error",
    "regexp/prefer-d": "error",
    "regexp/prefer-plus-quantifier": "error",
    "regexp/prefer-question-quantifier": "error",
    "regexp/prefer-star-quantifier": "error",
    "regexp/prefer-t": "error",
    "regexp/prefer-w": "error",
  },
};
