"use client";

export type { Icon as IconComp, IconProps } from "@phosphor-icons/react";
export {
  ArrowCircleUp as ArrowCircleUpIcon,
  CaretRight as CaretRightIcon,
  CheckCircle as CheckCircleIcon,
  Check as CheckIcon,
  Circle as CircleIcon,
  Columns as ColumnsIcon,
  Copy as CopyIcon,
  FileJs as FileJsIcon,
  FileTs as FileTsIcon,
  Laptop as LaptopIcon,
  Lightning as LightningIcon,
  MagicWand as MagicWandIcon,
  MagnifyingGlass as MagnifyingGlassIcon,
  MinusCircle as MinusCircleIcon,
  Moon as MoonIcon,
  PlusCircle as PlusCircleIcon,
  ShieldCheck as ShieldCheckIcon,
  Shield as ShieldIcon,
  ShieldSlash as ShieldSlashIcon,
  ShieldStar as ShieldStarIcon,
  ShieldWarning as ShieldWarningIcon,
  SketchLogo as SketchLogoIcon,
  Sparkle as SparkleIcon,
  Stack as StackIcon,
  Sun as SunIcon,
  Terminal as TerminalIcon,
  X as XIcon,
} from "@phosphor-icons/react";
